[package]
name = "radar-client-standalone"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.4.8", features = ["derive"] }
cs2 = { path = "../../cs2" }
cs2-schema-provider-impl = { path = "../../cs2-schema/provider-impl" }
env_logger = { workspace = true }
log = { workspace = true }
obfstr.workspace = true
radar-client = { path = "../client" }
radar-shared = { path = "../shared" }
tokio = { version = "1.34.0", features = ["io-util", "rt-multi-thread", "net", "signal"] }
url = "2.5.0"
utils-state = { path = "../../utils/state" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58.0", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Console",
    "Win32_System",
    "Foundation",
] }
